# 언어와 jdk의 버전을 지정한다.
language: java
jdk:
  - openjdk11

# 어느 브랜치가 push 될 때 수행할지 지정한다.
# 오직 main 브랜치가 push될 때 수행하도록 지정하였다.
branches:
  only:
    - main

# 빌드 전에 gradlew의 권한을 추가한다.
before_install:
  - chmod +x gradlew

# Travis CI 서버의 Home
# gradle을 통하여 의존성을 받게 되면 이를 캐시하여 배포할 때 마다 다시 받지 않도록 설정한다.
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

# main 브랜치에 push 되면 수행되는 명령어이다.
# 프로젝트 내에 권한이 추가된 gradlew를 활용하여 clean, build를 진행한다.
script: "./gradlew clean build"

# 배포 전 행위들을 선언한다.
before_deploy:
  # 현재 위치의 모든 파일을 runtou-application로 압축한다.
  - zip -r runtou-application *
  # deploy 디렉토리를 Travis가 실행 중인 위치에 생성한다.
  - mkdir -p deploy
  # 생성한 .zip 파일을 deploy 아래로 이동한다.
  - mv runtou-application.zip deploy/runtou-application.zip

# 외부 서비스와 연동할 행위들을 선언한다.
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis settings에 설정된 값
    bucket: runtou-build # S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리로 이동한다. 해당 위치의 파일만 이동시킨다.
    wait-until-deployed: true
    on:
      branch: main

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: runtou-build # S3 버킷
    key: runtou-application.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: runtou # 웹 콘솔에서 등록한 CodeDeploy 어플리케이션
    deployment_group: runtou-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2
    wait-until-deployed: true
    on:
      branch: main

# CI 실행 완료 시 작성한 슬랙으로 알람
notifications:
  slack: 4-siy3318:TxMKYJyfuXZv4wg0UgVQNimn